name: maps_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.0.6
  location: ^3.1.0
  geolocator: ^6.1.7
  flutter_compass: ^0.4.3
  get_it: ^5.0.1
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  json_annotation: ^3.0.0
  geocoding: ^1.0.5
  google_maps_place_picker: ^1.0.1
  firebase_admob: ^0.9.0+7
  firebase_core: 0.5.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.5.0
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  adaptive_icon_background: "#00000000"
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/north.png"
  image_path: "assets/north.png"

flutter:
  uses-material-design: true